export const PERMISSIONS = {
  VIEW_MEMBERS: "VIEW_MEMBERS",
  MANAGE_MEMBERS: "MANAGE_MEMBERS",
  MANAGE_ROLES: "MANAGE_ROLES",
  ASSIGN_ROLES: "ASSIGN_ROLES",
  REMOVE_ROLES: "REMOVE_ROLES",
  WARN_MEMBERS: "WARN_MEMBERS",
  MUTE_MEMBERS: "MUTE_MEMBERS",
  BAN_MEMBERS: "BAN_MEMBERS",
  DELETE_MESSAGES: "DELETE_MESSAGES",
  PIN_MESSAGES: "PIN_MESSAGES",
  MANAGE_AUTOMATIONS: "MANAGE_AUTOMATIONS",
  VIEW_ANALYTICS: "VIEW_ANALYTICS",
  MANAGE_SETTINGS: "MANAGE_SETTINGS",
  MANAGE_BOT: "MANAGE_BOT",
  VIEW_LOGS: "VIEW_LOGS"
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
